apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        component: api
    spec:
      containers:
        - name: golang-api
          image: siddartharyan180/golangtest:latest
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_HOST
              value: mongo-service
            - name: MONGO_PORT
              value: "27017"
