version: "3"
services:
  api:
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - "3000:3000"
    environment:
      MONGO_HOST: mongo-service
      MONGO_PORT: 27017
  mongo-service:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"